/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package javafx2340;

import java.net.URL;
import java.util.ResourceBundle;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.ListView;
import javafx.scene.control.ScrollPane;
import javafx.scene.layout.Background;
import javafx.scene.layout.Pane;
import javafx.scene.layout.StackPane;

/**
 * Java code to interface with the FXML generated by scene builder(could also be hand written).
 * @author Tyler Allen
 */
public class Controller implements Initializable {
    @FXML
    private ScrollPane scroll;
    @FXML
    private Button finish;
    @FXML
    private Label description;
    @Override
    public void initialize(URL url, ResourceBundle rb) {
         ObservableList<String> l = FXCollections.observableArrayList(
                "Item 1", "Item 2", "Item 3", "Item 4");
        scroll.setContent(new CharacterCreator(l));
        finish.setOnAction((ActionEvent event) -> {
            System.out.println("Finish");
        });
    }    
}
